---
# tasks for monitoring

- name: Ensure the destination directory exists on the remote machine -- tarraform/monitoring
  file:
    path: "{{remote_path}}/terraform/monitoring"
    state: directory

- name: Initialize Terraform
  command: terraform init
  args:
    chdir: "{{remote_path}}/terraform/monitoring"
  ignore_errors: true
  register: terraform_init

- name: Generate Terraform Plan
  command: terraform plan -out=tfplan
  args:
    chdir: "{{remote_path}}/terraform/monitoring"
  ignore_errors: true
  register: terraform_plan

- name: Deploy Terraform Infrastructure
  command: terraform apply -auto-approve tfplan
  args:
    chdir: "{{remote_path}}/terraform/monitoring"
  ignore_errors: true
  register: terraform_apply

- name: Handle Failure
  block:
    - name: Fail if Terraform Deployment Fails
      fail:
        msg: "Terraform deployment failed. Check logs for details."
      when: terraform_apply.rc != 0

    - name: Destroy Terraform Infrastructure on Failure
      command: terraform destroy -auto-approve
      args:
        chdir: "{{remote_path}}/terraform/monitoring"
      ignore_errors: true
      when: terraform_apply.rc != 0

  rescue:
    - name: Cleanup on Success or Failure
      command: terraform destroy -auto-approve
      args:
        chdir: "{{remote_path}}/terraform/monitoring"
      ignore_errors: true
      
  always:
    - name: Remove Terraform State Lock Files
      file:
        path: "{{remote_path}}/terraform/monitoring/.terraform.lock.info"
        state: absent
