---
# tasks for helm

- name: send helm installation script to server
  template:
    src: "install-helm.sh.j2"
    dest: "{{remote_path}}/install-helm.sh"
    mode: "0777"

- name: execute helm installation script
  command: "sh {{remote_path}}/install-helm.sh"
  
- name: print helm version
  debug:
    msg: "The current version of helm is {{helm_version}}"