---
# tasks for kind

- name: send kind installation script to server
  template:
    src: "install-kind.sh.j2"
    dest: "{{remote_path}}/install-kind.sh"
    mode: "0777"

- name: execute kind installation script
  command: "sh {{remote_path}}/install-kind.sh"
  
- name: print kind version
  debug:
    msg: "The current version of kind is {{kind_version}}"