---
# tasks for go

- name: Install Go
  golang:
    state: present

- name: verify go installation
  command: go version
  register: go_version
  changed_when: false

- name: print go version
  debug:
    msg: "Go version {{go_version.stdout}}"