---
# tasks for go

- name: make scripts directory
  file:
    path: "{{remote_path}}/scripts"
    state: directory

- name: send kind installation script to remote machine
  template:
    src: "install-go.sh.j2"
    dest: "{{remote_path}}/scripts/install-go.sh"
    mode: "0777"

- name: execute go installation script
  command: "sh {{remote_path}}/scripts/install-go.sh"

- name: verify go installation
  command: go version
  register: go_version
  changed_when: false

- name: print go version
  debug:
    msg: "Go version {{go_version.stdout}}"
