---
# tasks for node

- name: Install nodejs and npm
  apt:
    name: nodejs
    state: present

- name: verify nodejs installation
  command: node --version
  register: node_version
  changed_when: false

- name: verify npm installation
  command: npm --version
  register: npm_version
  changed_when: false

- name: print nodejs and npm versions
  debug:
    msg: "Node.js version: {{node_version.stdout}} | npm version: {{npm_version.stdout}}"