---
# tasks for deploy

- name: create a tar.bz2 archive for the deployment files on the local machine
  archive:
    path:
      - "{{local_path}}/k8s"
      - "{{local_path}}/terraform"
    dest: "{{local_path}}/deployment.tar.bz2"
    format: bz2
  delegate_to: localhost

- name: unarchived files on remote machine
  unarchive:
    src: "{{local_path}}/deployment.tar.bz2"
    dest: "{{remote_path}}"

- name: initialize terraform
  command: terraform init
  args:
    chdir: "{{remote_path}}/terraform/app"
  ignore_errors: true
  register: terraform_init

- name: generate terraform Plan
  command: terraform plan -out=tfplan
  args:
    chdir: "{{remote_path}}/terraform/app"
  ignore_errors: true
  register: terraform_plan

- name: deploy terraform app manifest files
  command: terraform apply -auto-approve tfplan
  args:
    chdir: "{{remote_path}}/terraform/app"
  ignore_errors: true
  register: terraform_apply