---
# task for docker

- name: package installation
  apt:
    name:
      - docker.io
      - python3-pip
    state: present
  tags:
    - install_packages

- name: starting docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - start_docker_service

- name: installing docker client for python
  pip:
    name: docker
    state: present
  tags:
    - install_docker_client

- name: verify docker installation
  command: docker -v
  register: docker_version
  changed_when: false

- name: print docker version
  debug:
    msg: "Docker version {{docker_version.stdout}}"
