---
# task for docker

- name: "Build - Package Installation"
  apt:
    name:
      - docker.io
      - python3-pip
    state: present
  tags:
    - install_packages

- name:  "Build - Starting Docker Service"
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - start_docker_service

- name: "Build - Installing Docker Client For Python"
  pip:
    name: docker
    state: present
  tags:
    - install_docker_client
