- name: configurations
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes
    #vars_files:
    #- vault/main.yml

  pre_tasks:
    - name: wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:

    - name: check if python is available
      stat:
        path: /usr/bin/python3
      register: python3_present

    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 300

  roles:
    # - docker
    - node
    - go
    - kind
    - helm
    - kubectl
    - terraform
      #- build
      #- deploy
      #- monitoring
