# This is a Kubernetes YAML configuration file that defines a Deployment resource.

apiVersion: apps/v1  # Specifies the API version for this Kubernetes resource.
kind: Deployment  # Defines the type of resource, in this case, a Deployment.

metadata:  # Metadata section for the Deployment resource.
  name: app-deployment  # The name assigned to this Deployment resource.

spec: # Specifies the desired state of the Deployment.
  replicas: 1 # Indicates that one replica Pod should be maintained.
  
  selector: # Defines how Pods are selected for this Deployment.
    matchLabels: # Labels to match Pods for this Deployment.
      app: app-deployment  # Pods with the label "app: app-deployment" will be selected.

  template: # Describes the Pod template to be used for creating new Pods.
    metadata: # Metadata for the Pod template.
      labels: # Labels assigned to Pods created from this template.
        app: app-deployment  # Pods created will have the label "app: app-deployment".

    spec: # Defines the specification for the Pods to be created.
      containers: # List of containers in the Pod.
        - name: app-deployment # Name of the container.
          image: maiempire/kind-app-2:latest # Docker image to use for this container.